name = "language"
description = "Headless language layer for GNAT Studio"
version = "0.1.0-dev"
project-files = ["language.gpr"]
licenses = "GPL-3.0-or-later"
authors = ["Rebecca"]
maintainers = ["Rebecca <rebecca@berkeleynerd.com>"]
maintainers-logins = ["berkeleynerd"]

[origin]
url = "git+file:/Users/rebecca/src/github.com/berkeleynerd/lsp_client_tmp/export_repos/language"
commit = "ef84b41bafcb9694b0d35967c01898f32391b668"
