name = "shared"
description = "Shared GPR with compiler/linker flags"
version = "0.1.0-dev"
project-files = ["shared.gpr"]
licenses = "GPL-3.0-or-later"
authors = ["Rebecca"]
maintainers = ["Rebecca <rebecca@berkeleynerd.com>"]
maintainers-logins = ["berkeleynerd"]

[origin]
url = "git+file:/Users/rebecca/src/github.com/berkeleynerd/lsp_client_tmp/export_repos/shared"
commit = "1863c713b3460a117e2e113a8a7dc1f8407d11d4"
